### PR TITLE
fix: rp-adapter ui

### PR DESCRIPTION
**Pull request by llorllale**
Fix RP Adapter UI (trustbloc/edge-adapter#200)

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

**Comment by rolsonquadras** [comment]
@llorllale Did you run the sandbox demo ? I see that the merge build for https://github.com/trustbloc/edge-adapter/issues/200 has failed - https://dev.azure.com/trustbloc/edge/_build/results?buildId=6148&view=results.

**Comment by llorllale** [comment]
@rolsonquadras 

> @llorllale Did you run the sandbox demo to verify the changes for [trustbloc/edge-adapter#20](https://github.com/trustbloc/edge-adapter/pull/20) ? I see that the merge build for [trustbloc/edge-adapter#200](https://github.com/trustbloc/edge-adapter/issues/200) has failed - https://dev.azure.com/trustbloc/edge/_build/results?buildId=6148&view=results.

I'll fix the lint error over there. This shouldn't block this PR.

**Comment by rolsonquadras** [comment]
> @rolsonquadras
> 
> > @llorllale Did you run the sandbox demo to verify the changes for [trustbloc/edge-adapter#20](https://github.com/trustbloc/edge-adapter/pull/20) ? I see that the merge build for [trustbloc/edge-adapter#200](https://github.com/trustbloc/edge-adapter/issues/200) has failed - https://dev.azure.com/trustbloc/edge/_build/results?buildId=6148&view=results.
> 
> I'll fix the lint error over there. This shouldn't block this PR.

Then the PR description needs to be updated as this PR doesn't contain updates mentioned in trustbloc/edge-adapter#20, right ?

**Comment by llorllale** [comment]
@rolsonquadras 

> > @rolsonquadras
> > > @llorllale Did you run the sandbox demo to verify the changes for [trustbloc/edge-adapter#20](https://github.com/trustbloc/edge-adapter/pull/20) ? I see that the merge build for [trustbloc/edge-adapter#200](https://github.com/trustbloc/edge-adapter/issues/200) has failed - https://dev.azure.com/trustbloc/edge/_build/results?buildId=6148&view=results.
> > 
> > 
> > I'll fix the lint error over there. This shouldn't block this PR.
> 
> Then the PR description needs to be updated as this PR doesn't contain updates mentioned in [trustbloc/edge-adapter#20](https://github.com/trustbloc/edge-adapter/pull/20), right ?

Fixing the error over there...

**Comment by llorllale** [comment]
@rolsonquadras fix in trustbloc/edge-adapter#207 please approve

**Comment by llorllale** [comment]
@rolsonquadras please verify now

**Pull request merged**
