### PR TITLE
chore: Updates edge-agent, hub-router and adapters(rp,issuer) versions

### PR DESCRIPTION
**Pull request by soluchok**
Updates edge-agent, hub-router and adapters(rp,issuer) versions.

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

**Review by troyronda — APPROVED** [review]

**Review by llorllale — APPROVED** [review]

**Comment by llorllale** [comment]
@soluchok did you verify the demo flows?

**Comment by soluchok** [comment]
@troyronda @rolsonquadras @sudeshrshetty @llorllale I have not checked it yet. If someone has a chance to check it let me know. If not I will try to check it soon :)

**Review by rolsonquadras — CHANGES_REQUESTED** [review]
Demo fails with following error:

> issuer.adapter.rest.example.com   | [aries-framework/issuecredential/service] 2020/10/29 19:58:37 UTC - issuecredential.(*Service).startInternalListener -> ERROR abandoning: handle https://didcomm.org/issue-credential/2.0/request-credential : subject did is missing in authorization cred request

Marking this as Request Change for now, as to stop this from getting merged by mistake.

**Comment by rolsonquadras** [comment]
> Demo fails with following error:
> 
> > issuer.adapter.rest.example.com   | [aries-framework/issuecredential/service] 2020/10/29 19:58:37 UTC - issuecredential.(*Service).startInternalListener -> ERROR abandoning: handle https://didcomm.org/issue-credential/2.0/request-credential : subject did is missing in authorization cred request
> 
> Marking this as Request Change for now, as to stop this from getting merged by mistake.

Pushed the [changes](https://github.com/trustbloc/edge-sandbox/compare/a925a7904dc94c351ca9d7e2c836eacfacd41011..5066b471e95db0dca5b023430861f970fb031420) with new images for wallet and adapter.

Verified these changes locally.

**Review by rolsonquadras — APPROVED** [review]

**Comment by soluchok** [comment]
> Verified these changes locally.

@rolsonquadras Thanks.

**Pull request merged**
